### PR TITLE
Start adding tests

### PR DESCRIPTION
**Pull request by ThomWright**
Summary of changes:

- Use a default Mongo URL if no environment variable found
- Simple tests for HTTP APIs using [Mocha](http://mochajs.org/) and [SuperTest](https://github.com/visionmedia/supertest)
- More meaningful HTTP response codes (e.g. 201 Created after creating new user)
- Better Vagrant provisioning

Note: I'm using Travis on my fork: https://travis-ci.org/ThomWright/registry-server

If you like these, I'll start adding some more tests soon. Let me know what you think :)

### CODE REVIEW

**Comment by ThomWright** [comment]
@thomasdavis Any feedback or chance of merging this soon? My aim is to:

- add some more tests
- do a bit of refactoring
- add a password reset feature

I've forgotten my password so it'd be great to get this through ASAP.

**Comment by mchelen** [comment]
I'll try to get this PR tested ASAP

**Comment by thomasdavis** [comment]
Sorry,  this one slipped through the cracks! Will also review...

**Comment by ThomWright** [comment]
Great, thanks guys :)

**Comment by ThomWright** [comment]
Any progress with this?

**Comment by thomasdavis** [comment]
Very very sorry, for the past 6 months I've been struggling with some personal issues and unable to keep up to speed with some projects. 

I'm reviewing this from start to finish right now ;) stay tuned. (it looks like great work)

**Comment by thomasdavis** [comment]
Lots of great work here, as above sorry about the delays. Adding a Travis badge now to the README ^^

**Comment by ThomWright** [comment]
No worries! I had to drop out of open source stuff ~6 months ago because of personal issues too. I hope things are looking up.

Raised #43 for the test db stuff.

**Pull request merged**
