### PR TITLE
Proposal to start using Mongoose

### PR DESCRIPTION
**Pull request by rolandnsharp**
This PR is a work in progress.

Sorry for mixing all these indentation changes into this PR, I didn't realise my editor was beautifying.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I think node's version should be set in package.json not nvmrc, not everybody use nvm.

**Comment by rolandnsharp** [comment]
thanks @PeterDaveHello , I've added it to the package.json now.

**Comment by rolandnsharp** [comment]
No Idea why Travis is failing. It's returning: `The command "git submodule update --init --recursive" failed and exited with 1 during .`

**Comment by rolandnsharp** [comment]
This PR is too messy. Going to start again.

**Pull request closed without merging**
